server:
      port: 8081
spring:
      application:
            name: Gateway
      cloud:
            consul:
                  host: mxem_consul_1
                  port: 8500
                  config:
                        failFast: true
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

---
spring:
  profiles: zone1
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        instanceZone: zone1
        register: false
        registerHealthCheck: false
        tags: zone=zone1