server:
  port: 8083

spring:
  application:
    name: Environments
    cloud:
      consul:
        host: consul
        port: 8500
        config:
          failFast: true

logging:
  file: logs/ordesr.log
  level:
    #    com.netflix: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  pattern:
    #    console: "%d{HH:mm:ss.SSS} %-5level %msg%n"
    file: "%d{HH:mm:ss.SSS} %-5level %msg%n"

---
spring:
  profiles: zone1
  cloud:
    consul:
      discovery:
        instanceZone: zone1

